import 'package:geolocator/geolocator.dart';

class MockLocationDetector {
  /// Detects if the current position is generated by a mock provider (Fake GPS app)
  static bool isMockPosition(Position position) {
    return position.isMocked;
  }

  /// Verifies GPS horizontal accuracy to prevent spoofing with artificial coordinates
  static bool isAccuracyAcceptable(Position position, {double maxThresholdMeters = 35.0}) {
    return position.accuracy <= maxThresholdMeters;
  }
}
